// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/AwsSdkCrt.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_callback
NumericVector test_callback(NumericVector numvec, Function f);
RcppExport SEXP _AwsSdkCrt_test_callback(SEXP numvecSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type numvec(numvecSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(test_callback(numvec, f));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_make_internal
XPtr< Wrapper > rcpp_make_internal();
RcppExport SEXP _AwsSdkCrt_rcpp_make_internal() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_make_internal());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_use_internal
int rcpp_use_internal(XPtr< Wrapper > p);
RcppExport SEXP _AwsSdkCrt_rcpp_use_internal(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr< Wrapper > >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_use_internal(p));
    return rcpp_result_gen;
END_RCPP
}
// aws_credentials_from_chain
uint32_t aws_credentials_from_chain();
RcppExport SEXP _AwsSdkCrt_aws_credentials_from_chain() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(aws_credentials_from_chain());
    return rcpp_result_gen;
END_RCPP
}
// aws_error_debug_str
String aws_error_debug_str(int err);
RcppExport SEXP _AwsSdkCrt_aws_error_debug_str(SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type err(errSEXP);
    rcpp_result_gen = Rcpp::wrap(aws_error_debug_str(err));
    return rcpp_result_gen;
END_RCPP
}
// aws_error_name
String aws_error_name(int err);
RcppExport SEXP _AwsSdkCrt_aws_error_name(SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type err(errSEXP);
    rcpp_result_gen = Rcpp::wrap(aws_error_name(err));
    return rcpp_result_gen;
END_RCPP
}
// aws_error_str
String aws_error_str(int err);
RcppExport SEXP _AwsSdkCrt_aws_error_str(SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type err(errSEXP);
    rcpp_result_gen = Rcpp::wrap(aws_error_str(err));
    return rcpp_result_gen;
END_RCPP
}
// aws_last_error
int aws_last_error();
RcppExport SEXP _AwsSdkCrt_aws_last_error() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(aws_last_error());
    return rcpp_result_gen;
END_RCPP
}
// aws_test_error
int aws_test_error(int err);
RcppExport SEXP _AwsSdkCrt_aws_test_error(SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type err(errSEXP);
    rcpp_result_gen = Rcpp::wrap(aws_test_error(err));
    return rcpp_result_gen;
END_RCPP
}
// aws_crc32
uint32_t aws_crc32(StringVector input, uint32_t previous);
RcppExport SEXP _AwsSdkCrt_aws_crc32(SEXP inputSEXP, SEXP previousSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type previous(previousSEXP);
    rcpp_result_gen = Rcpp::wrap(aws_crc32(input, previous));
    return rcpp_result_gen;
END_RCPP
}
// aws_crc32c
uint32_t aws_crc32c(StringVector input, uint32_t previous);
RcppExport SEXP _AwsSdkCrt_aws_crc32c(SEXP inputSEXP, SEXP previousSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type previous(previousSEXP);
    rcpp_result_gen = Rcpp::wrap(aws_crc32c(input, previous));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_handcoded_aws_checksums_crc32
uint32_t rcpp_handcoded_aws_checksums_crc32(StringVector input, uint32_t previous);
RcppExport SEXP _AwsSdkCrt_rcpp_handcoded_aws_checksums_crc32(SEXP inputSEXP, SEXP previousSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type previous(previousSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_handcoded_aws_checksums_crc32(input, previous));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_aws_crt_init
void rcpp_aws_crt_init();
RcppExport SEXP _AwsSdkCrt_rcpp_aws_crt_init() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_aws_crt_init();
    return R_NilValue;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _AwsSdkCrt_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// warble_garble
List warble_garble();
RcppExport SEXP _AwsSdkCrt_warble_garble() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(warble_garble());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_sum
double rcpp_sum(NumericVector v);
RcppExport SEXP _AwsSdkCrt_rcpp_sum(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_sum(v));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_CrtModule();
RcppExport SEXP _rcpp_module_boot_play();

static const R_CallMethodDef CallEntries[] = {
    {"_AwsSdkCrt_test_callback", (DL_FUNC) &_AwsSdkCrt_test_callback, 2},
    {"_AwsSdkCrt_rcpp_make_internal", (DL_FUNC) &_AwsSdkCrt_rcpp_make_internal, 0},
    {"_AwsSdkCrt_rcpp_use_internal", (DL_FUNC) &_AwsSdkCrt_rcpp_use_internal, 1},
    {"_AwsSdkCrt_aws_credentials_from_chain", (DL_FUNC) &_AwsSdkCrt_aws_credentials_from_chain, 0},
    {"_AwsSdkCrt_aws_error_debug_str", (DL_FUNC) &_AwsSdkCrt_aws_error_debug_str, 1},
    {"_AwsSdkCrt_aws_error_name", (DL_FUNC) &_AwsSdkCrt_aws_error_name, 1},
    {"_AwsSdkCrt_aws_error_str", (DL_FUNC) &_AwsSdkCrt_aws_error_str, 1},
    {"_AwsSdkCrt_aws_last_error", (DL_FUNC) &_AwsSdkCrt_aws_last_error, 0},
    {"_AwsSdkCrt_aws_test_error", (DL_FUNC) &_AwsSdkCrt_aws_test_error, 1},
    {"_AwsSdkCrt_aws_crc32", (DL_FUNC) &_AwsSdkCrt_aws_crc32, 2},
    {"_AwsSdkCrt_aws_crc32c", (DL_FUNC) &_AwsSdkCrt_aws_crc32c, 2},
    {"_AwsSdkCrt_rcpp_handcoded_aws_checksums_crc32", (DL_FUNC) &_AwsSdkCrt_rcpp_handcoded_aws_checksums_crc32, 2},
    {"_AwsSdkCrt_rcpp_aws_crt_init", (DL_FUNC) &_AwsSdkCrt_rcpp_aws_crt_init, 0},
    {"_AwsSdkCrt_rcpp_hello_world", (DL_FUNC) &_AwsSdkCrt_rcpp_hello_world, 0},
    {"_AwsSdkCrt_warble_garble", (DL_FUNC) &_AwsSdkCrt_warble_garble, 0},
    {"_AwsSdkCrt_rcpp_sum", (DL_FUNC) &_AwsSdkCrt_rcpp_sum, 1},
    {"_rcpp_module_boot_CrtModule", (DL_FUNC) &_rcpp_module_boot_CrtModule, 0},
    {"_rcpp_module_boot_play", (DL_FUNC) &_rcpp_module_boot_play, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_AwsSdkCrt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
