# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_aws_checksums_crc32 <- function(input, previous) {
    .Call(`_AwsSdkCrt_rcpp_aws_checksums_crc32`, input, previous)
}

rcpp_aws_checksums_crc32c <- function(input, previous) {
    .Call(`_AwsSdkCrt_rcpp_aws_checksums_crc32c`, input, previous)
}

rcpp_handcoded_aws_checksums_crc32 <- function(input, previous = 0L) {
    .Call(`_AwsSdkCrt_rcpp_handcoded_aws_checksums_crc32`, input, previous)
}

rcpp_hello_world <- function() {
    .Call(`_AwsSdkCrt_rcpp_hello_world`)
}

warble_garble <- function() {
    .Call(`_AwsSdkCrt_warble_garble`)
}

rcpp_sum <- function(v) {
    .Call(`_AwsSdkCrt_rcpp_sum`, v)
}

