# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_callback <- function(numvec, f) {
    .Call(`_AwsSdkCrt_test_callback`, numvec, f)
}

rcpp_make_internal <- function() {
    .Call(`_AwsSdkCrt_rcpp_make_internal`)
}

rcpp_use_internal <- function(p) {
    .Call(`_AwsSdkCrt_rcpp_use_internal`, p)
}

aws_credentials_from_chain <- function() {
    .Call(`_AwsSdkCrt_aws_credentials_from_chain`)
}

aws_error_debug_str <- function(err) {
    .Call(`_AwsSdkCrt_aws_error_debug_str`, err)
}

aws_error_name <- function(err) {
    .Call(`_AwsSdkCrt_aws_error_name`, err)
}

aws_error_str <- function(err) {
    .Call(`_AwsSdkCrt_aws_error_str`, err)
}

aws_last_error <- function() {
    .Call(`_AwsSdkCrt_aws_last_error`)
}

aws_test_error <- function(err) {
    .Call(`_AwsSdkCrt_aws_test_error`, err)
}

aws_crc32 <- function(input, previous) {
    .Call(`_AwsSdkCrt_aws_crc32`, input, previous)
}

aws_crc32c <- function(input, previous) {
    .Call(`_AwsSdkCrt_aws_crc32c`, input, previous)
}

rcpp_handcoded_aws_checksums_crc32 <- function(input, previous = 0L) {
    .Call(`_AwsSdkCrt_rcpp_handcoded_aws_checksums_crc32`, input, previous)
}

rcpp_aws_crt_init <- function() {
    invisible(.Call(`_AwsSdkCrt_rcpp_aws_crt_init`))
}

rcpp_hello_world <- function() {
    .Call(`_AwsSdkCrt_rcpp_hello_world`)
}

warble_garble <- function() {
    .Call(`_AwsSdkCrt_warble_garble`)
}

rcpp_sum <- function(v) {
    .Call(`_AwsSdkCrt_rcpp_sum`, v)
}

