# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_make_internal <- function() {
    .Call(`_AwsSdkCrt_rcpp_make_internal`)
}

rcpp_use_internal <- function(p) {
    .Call(`_AwsSdkCrt_rcpp_use_internal`, p)
}

rcpp_hc_get_credentials <- function() {
    .Call(`_AwsSdkCrt_rcpp_hc_get_credentials`)
}

rcpp_aws_error_debug_str <- function(err) {
    .Call(`_AwsSdkCrt_rcpp_aws_error_debug_str`, err)
}

rcpp_aws_error_name <- function(err) {
    .Call(`_AwsSdkCrt_rcpp_aws_error_name`, err)
}

rcpp_aws_error_str <- function(err) {
    .Call(`_AwsSdkCrt_rcpp_aws_error_str`, err)
}

rcpp_aws_last_error <- function() {
    .Call(`_AwsSdkCrt_rcpp_aws_last_error`)
}

rcpp_aws_test_error <- function(err) {
    .Call(`_AwsSdkCrt_rcpp_aws_test_error`, err)
}

rcpp_aws_crc32 <- function(input, previous) {
    .Call(`_AwsSdkCrt_rcpp_aws_crc32`, input, previous)
}

rcpp_aws_crc32c <- function(input, previous) {
    .Call(`_AwsSdkCrt_rcpp_aws_crc32c`, input, previous)
}

rcpp_handcoded_aws_checksums_crc32 <- function(input, previous = 0L) {
    .Call(`_AwsSdkCrt_rcpp_handcoded_aws_checksums_crc32`, input, previous)
}

rcpp_aws_crt_init <- function() {
    invisible(.Call(`_AwsSdkCrt_rcpp_aws_crt_init`))
}

awshc_test_error <- function(error) {
    .Call(`_AwsSdkCrt_awshc_test_error`, error)
}

awshc_error_string <- function(error) {
    .Call(`_AwsSdkCrt_awshc_error_string`, error)
}

rcpp_hello_world <- function() {
    .Call(`_AwsSdkCrt_rcpp_hello_world`)
}

warble_garble <- function() {
    .Call(`_AwsSdkCrt_warble_garble`)
}

rcpp_sum <- function(v) {
    .Call(`_AwsSdkCrt_rcpp_sum`, v)
}

